# Sonic Pi playback function and usage example
# for a sample pack generated by synth.is
# published at
# https://synth.is/pub/sound/01eb1sh43v5ks1e4j0aj9phfbk_13_11_FM-AM-filter-distortion_6000

########### sample pack playback function

gated_distorted_realm_1596725652_sample_pack_parent_folder = "~/samples"
gated_distorted_realm_1596725652_sample_pack = "#{gated_distorted_realm_1596725652_sample_pack_parent_folder}/synth_is_01eb1sh43v5ks1e4j0aj9phfbk_13_11_FM-AM-filter-distortion_6000/01eb1sh43v5ks1e4j0aj9phfbk_13_11_FM-AM-filter-distortion_6000__samples/"

define :gated_distorted_realm_1596725652_player do |note, velocity, opts={}|
  sample gated_distorted_realm_1596725652_sample_pack, note.is_a?(Numeric) ? "midi#{note}" : "note#{note}", "vel#{velocity}", opts
end

wobbly_bell_1597012625_sample_pack_parent_folder = "~/samples"
wobbly_bell_1597012625_sample_pack = "#{wobbly_bell_1597012625_sample_pack_parent_folder}/synth_is_01e15c41ppg4x755ywhd1fjgz0_15_8_01e06cwp31sdn3dzmxz4n2qk4m_19000/01e15c41ppg4x755ywhd1fjgz0_15_8_01e06cwp31sdn3dzmxz4n2qk4m_19000__samples/"

define :wobbly_bell_1597012625_player do |note, velocity, opts={}|
  sample wobbly_bell_1597012625_sample_pack, note.is_a?(Numeric) ? "midi#{note}" : "note#{note}", "vel#{velocity}", opts
end

wobbly_bell_1900_sample_pack_parent_folder = "~/samples"
wobbly_bell_1900_sample_pack = "#{wobbly_bell_1900_sample_pack_parent_folder}/synth_is_01e15c41ppg4x755ywhd1fjgz0_15_8_01e06cwp31sdn3dzmxz4n2qk4m_1900/01e15c41ppg4x755ywhd1fjgz0_15_8_01e06cwp31sdn3dzmxz4n2qk4m_1900__samples/"

define :wobbly_bell_1900_player do |note, velocity, opts={}|
  sample wobbly_bell_1900_sample_pack, note.is_a?(Numeric) ? "midi#{note}" : "note#{note}", "vel#{velocity}", opts
end


########### example usage

gated_distorted_realm_1596725652_duration = 6.00
gated_distorted_realm_1596725652_sleep = gated_distorted_realm_1596725652_duration / 1.65
gated_distorted_realm_1596725652_attack = 0.01
gated_distorted_realm_1596725652_release = 1
gated_distorted_realm_1596725652_start = 0
gated_distorted_realm_1596725652_finish = 0.7

gated_distorted_realm_1596725652_velocities =
  [15,31,47,63,79,95,111,127].ring.butlast.stretch(2).reflect
two_tone_names = ["F4","A4"].ring
kick_sleep = 0.454
kick_sleep_multi = 1

twoTonePlayerOpts = {
  attack: gated_distorted_realm_1596725652_attack,
  release: gated_distorted_realm_1596725652_release,
  # start: gated_distorted_realm_1596725652_start,
  finish: gated_distorted_realm_1596725652_finish,
  start: 0.05
}

live_loop :link, delay: 0.01 do # about that delay: https://in-thread.sonic-pi.net/t/live-loops-sync-questions/1172/13
  sleep gated_distorted_realm_1596725652_sleep
end


live_loop :two_tone do
  stop if 0 == 0
  sync :link
  s = gated_distorted_realm_1596725652_player two_tone_names.tick(:two_tone_note_tick),
    gated_distorted_realm_1596725652_velocities.tick(:two_tone_vel_tick),
    twoTonePlayerOpts.merge({cutoff: 95, amp: 1.0, start: 0.06})
  control s, cutoff_slide: 4, cutoff: 40
  sleep gated_distorted_realm_1596725652_sleep - 0.1
end

two_tone_names_b = ["F5","C5"].ring
live_loop :two_tone_b do
  stop if 0 == 0
  sync :link
  # sleep rrand(0.005, 0.01)
  sleep 0.01
  s = gated_distorted_realm_1596725652_player two_tone_names_b.tick(:two_tone_b_note_tick),
    gated_distorted_realm_1596725652_velocities.tick(:two_tone_b_vel_tick),
    twoTonePlayerOpts.merge({cutoff:95, amp: 1.0})
  control s, cutoff_slide: 4, cutoff: 35
  sleep gated_distorted_realm_1596725652_sleep - 0.1
end


live_loop :kick do
  stop if 0 == 0
  sync :link
  (8*kick_sleep_multi).round.times do
    sample :bd_haus,
      cutoff: rrand(66, 90),
      #cutoff: 100,
      amp: 0.8
    sleep kick_sleep / kick_sleep_multi
  end
end

live_loop :drums do
  stop if 0 == 0
  with_fx :wobble, phase: 0.25, wave: 0, res: 0.5, mix:0.0 do
    with_fx :flanger, feedback: 0.1, decay: 2, delay: 5, depth: 5, mix:0 do
      sync :link
      use_random_seed 8 # 9, 10, 11
      (32*kick_sleep_multi).times do
        sample :bd_haus, rate: 0.35, cutoff: 80, amp: 0.7 if rand < 0.35
        sleep (kick_sleep * 0.25)
      end
    end
  end
end


with_fx :echo, phase: 0.125, mix: 0.4 do
  live_loop :cymbal do
    stop if 0 == 0
    sync :link
    (16
     #     *kick_sleep_multi
    ).round.times do
      sample :drum_cymbal_soft, sustain: 0, release: 0.1, hpf_attack:0.6, amp:0.6, cutoff: 110
      sleep kick_sleep / 2 # / kick_sleep_multi
    end
  end
end


# https://synth.is/pub/sound/01e15c41ppg4x755ywhd1fjgz0_15_8_01e06cwp31sdn3dzmxz4n2qk4m_19000

wobbly_bell_1597012625_midi_note_number_start = 48
wobbly_bell_1597012625_midi_note_number_end = 83
wobbly_bell_1597012625_note_names = ["C3","C#3","D3","D#3","E3","F3","F#3","G3","G#3","A3","A#3","B3","C4","C#4","D4","D#4","E4","F4","F#4","G4","G#4","A4","A#4","B4","C5","C#5","D5","D#5","E5","F5","F#5","G5","G#5","A5","A#5","B5"]
wobbly_bell_1597012625_velocities = [15,31,47,63,79,95,111,127].ring.reverse
wobbly_bell_1597012625_duration = 19.00
wobbly_bell_1597012625_sleep = wobbly_bell_1597012625_duration / 4
wobbly_bell_1597012625_attack = 0.01
wobbly_bell_1597012625_release = 0.1
wobbly_bell_1597012625_start = 0
wobbly_bell_1597012625_finish = 1
wobbly_bell_notes = ["E5","G5","C5","A4"].ring

wobblyBell_1597012625_playerOpts = {
  attack: wobbly_bell_1597012625_attack,
  release: wobbly_bell_1597012625_release,
  start: wobbly_bell_1597012625_start,
  finish: wobbly_bell_1597012625_finish
}

live_loop :wobbly_bell do
  stop if 0 == 0
  sync :link
  with_fx :echo do
    with_fx :slicer, phase: 0.125, wave: 2, mix: 1.0 do
      wobbly_bell_1597012625_player wobbly_bell_notes.tick(:wobbly_bell_note_tick),
        wobbly_bell_1597012625_velocities.tick(:wobbly_bell_vel_tick),
        wobblyBell_1597012625_playerOpts.merge({amp: 0.5, cutoff: 100})
      sleep gated_distorted_realm_1596725652_sleep - 0.1
    end
  end
end

# https://synth.is/pub/sound/01e15c41ppg4x755ywhd1fjgz0_15_8_01e06cwp31sdn3dzmxz4n2qk4m_1900

wobbly_bell_1900_midi_note_number_start = 48
wobbly_bell_1900_midi_note_number_end = 83
wobbly_bell_1900_note_names = ["C3","C#3","D3","D#3","E3","F3","F#3","G3","G#3","A3","A#3","B3","C4","C#4","D4","D#4","E4","F4","F#4","G4","G#4","A4","A#4","B4","C5","C#5","D5","D#5","E5","F5","F#5","G5","G#5","A5","A#5","B5"]
wobbly_bell_1900_velocities = [15,31,47,63,79,95,111,127]
wobbly_bell_1900_duration = 1.90
wobbly_bell_1900_sleep = wobbly_bell_1900_duration / 4
wobbly_bell_1900_attack = 0.03
wobbly_bell_1900_release = 0.03
wobbly_bell_1900_start = 0
wobbly_bell_1900_finish = 1
wobbly_bell_lead_notes = [
  "A4",
  "C5",
  "F5",
  "G5",
  "A5"  # <- end at
].ring

wobblyBell_1900_playerOpts = {
  attack: wobbly_bell_1900_attack,
  release: wobbly_bell_1900_release,
  sustain: 0.06,
  # start: wobbly_bell_1900_start,
  # finish: wobbly_bell_1900_finish
}

live_loop :wobbly_bell_lead do
  stop if 0 == 1
  sync :link
  use_random_seed 1 # 111
  with_fx :reverb, room: 1, amp:2 do
    15.times do
      wobbly_bell_1900_player wobbly_bell_lead_notes.choose, wobbly_bell_1900_velocities.choose, wobblyBell_1900_playerOpts
      sleep gated_distorted_realm_1596725652_sleep / 16
    end
  end
end
